export const ActionTypes = {
  NOTE: {
    CHANGE_EDIT_MODE: 'CHANGE_EDIT_MODE',
    CREATE_CATEGORY: 'CREATE_CATEGORY',
    SAVE_NOTE_TEXT: 'SAVE_NOTE_TEXT',
    SET_SELECTED_CATEGORY: 'SET_SELECTED_CATEGORY',
    CREATE_NOTE: 'CREATE_NOTE'
  }
}
